import type { Metadata } from 'next';
import { Lora } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/landing/navbar/navbar';
import ScrollUp from '@/components/landing/scrollup';

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} antialiased`}>
        <Navbar />
        <ScrollUp />
        {children}
      </body>
    </html>
  );
}
